steps:
  - name: 'maven:3-jdk-11'
    args:
      - '-c'
      - >
        mvn package -Dmaven.test.skip=true -f pom.xml
    entrypoint: bash
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/${PROJECT_ID}/parsecfdi', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push','gcr.io/${PROJECT_ID}/parsecfdi']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'parsecfdi', '--region=us-central1', '--platform', 'managed', '--allow-unauthenticated', '--image=gcr.io/${PROJECT_ID}/unilease-front-qa:$SHORT_SHA']
options:
  logging: CLOUD_LOGGING_ONLY
