steps:
  - name: 'maven:3-jdk-8'
    args:
      - '-c'
      - >
        ls
        mvn package -Dmaven.test.skip=true -f parsecfdi/pom.xml
        cp parsecfdi/target/parsecfdi-0.0.1-SNAPSHOT.jar deploy/dev/parsecfdi.jar
    entrypoint: bash
  - name: gcr.io/cloud-builders/docker
    args:
      - '-c'
      - >
        date -u +%Y%m%dT%H%M%S > .tag
        docker build -t gcr.io/${PROJECT_ID}/${_REPO_NAME}:${BUILD_ID} .
        docker push gcr.io/${PROJECT_ID}/${_REPO_NAME}:${BUILD_ID}
    dir: deploy/dev/
    entrypoint: bash
options:
  logging: CLOUD_LOGGING_ONLY
