steps:
  - name: 'maven:3-jdk-11'
    args:
      - '-c'
      - >
        mvn package -Dmaven.test.skip=true -f pom.xml
    entrypoint: bash
  - name: gcr.io/cloud-builders/docker
    args:
      - '-c'
      - >
        date -u +%Y%m%dT%H%M%S > .tag
        docker build -t gcr.io/${PROJECT_ID}/${_REPO_NAME}:${BUILD_ID} .
        docker push gcr.io/${PROJECT_ID}/${_REPO_NAME}:${BUILD_ID}
    entrypoint: bash
options:
  logging: CLOUD_LOGGING_ONLY
